require 'test_helper'

# ControllerTest generated by Typus, use it to test the extended admin functionality.
class Admin::NewslettersControllerTest < ActionController::TestCase

  fixtures(:typus_users)

  context "an user logged in and HTTP_REFERER set" do
    setup do
      @request.session[:typus_user_id] = typus_users(:admin).id
      @request.env["HTTP_REFERER"] = "/admin"
    end
    
    context "requesting GET :invite_to_beta which send invitation" do
      setup do
        Newsletter.any_instance.stubs(:invite_to_beta).returns(true)
        get :invite_to_beta, :id => Newsletter.make.id
      end
            
      should_respond_with(:redirect)
      should_redirect_to("newsletters list") { "/admin/newsletters" }
      
      should_set_the_flash(:success)
    end
    
    context "requesting GET :invite_to_beta which fail" do
      setup do
        Newsletter.any_instance.stubs(:invite_to_beta).returns(false)
        get :invite_to_beta, :id => Newsletter.make.id
      end
      
      should_respond_with(:redirect)
      should_redirect_to("back") { "/admin" }
      
      should_set_the_flash(:error)
    end
    
    context "requesting GET :boost_activation which send boost" do
      setup do
        Newsletter.any_instance.stubs(:boost_activation).returns(true)
        get :boost_activation, :id => Newsletter.make.id
      end
            
      should_respond_with(:redirect)
      should_redirect_to("newsletters list") { "/admin/newsletters" }
      
      should_set_the_flash(:success)
    end
    
    context "requesting GET :boost_activation which fail" do
      setup do
        Newsletter.any_instance.stubs(:boost_activation).returns(false)
        get :boost_activation, :id => Newsletter.make.id
      end
      
      should_respond_with(:redirect)
      should_redirect_to("back") { "/admin" }
      
      should_set_the_flash(:error)
    end    
  end
end