# Controller generated by Typus, use it to extend admin functionality.
class Admin::BetaCodesController < Admin::MasterController

  def boost_activation
    bc = BetaCode.find(params[:id])
    if bc.boost_activation
      flash[:success] = "Relance envoyée !"
      redirect_to(:action => :index)
    else
      flash[:error] = "Déjà activé !"
      redirect_to(:back)
    end
  end

end
