# Controller generated by Typus, use it to extend admin functionality.
class Admin::NewslettersController < Admin::MasterController

  def invite_to_beta
    nl = Newsletter.find(params[:id])
    if nl.invite_to_beta
      flash[:success] = "Invitation envoyée !"
      redirect_to(:action => :index)      
    else
      flash[:error] = "Déjà invité ou non activé !"
      redirect_to(:back)      
    end
  end
  
  def boost_activation
    nl = Newsletter.find(params[:id])
    if nl.boost_activation
      flash[:success] = "Relance envoyée !"
      redirect_to(:action => :index)      
    else
      flash[:error] = "Déjà activé !"
      redirect_to(:back)      
    end
  end

end
