# Controller generated by Typus, use it to extend admin functionality.
class Admin::UsersController < Admin::MasterController

  def boost_activation
    u = User.find(params[:id])
    if u.boost_activation
      flash[:success] = "Relance envoyée !"
      redirect_to(:action => :index)
    else
      flash[:error] = "Déjà activé !"
      redirect_to(:back)
    end    
  end

end
