#= require jquery
#= require jquery-migrate
#= require jquery-ujs
#= require jquery-ui
#= require jquery-ui/ui/datepicker
#= require jquery-ui/ui/i18n/datepicker-fr
#= require jquery-ui/ui/slider
#= require jquery-ui/ui/accordion
#= require jquery-ui/ui/autocomplete
#= require common
#= require back/FixedColumns.min.js
#= require back/moment.min.js
#= require back/moment-timezone-with-data.min.js
#= require back/moment-timezone.min.js
#= require back/fullcalendar.min.js
#= require back/fullcalendar-fr.js
#= require back/GrowingInput.js
#= require back/jquery-ui-timepicker-addon.js
#= require back/jquery-ui-timepicker-fr.js
#= require back/jquery.dataTables.min.js
#= require back/jquery.pstrength.1.2.js
#= require back/tag-it.min.js
#= require bootstrap
#= require back/highcharts/highcharts
#= require back/highcharts/highcharts-more
#= require back/back

#= require_self
