#= require jquery
#= require jquery-migrate
#= require jquery-ujs
#= require jquery-ui
#= require jquery-ui/ui/datepicker
#= require jquery-ui/ui/i18n/datepicker-fr
#= require jquery-ui/ui/slider
#= require jquery-ui/ui/accordion
#= require jquery-ui/ui/autocomplete
#= require common
#= require datatables
#= require datatables-fixedcolumns
#= require moment
#= require moment-timezone/moment-timezone-with-data
#= require fullcalendar
#= require fullcalendar/lang/fr
#= require back/jquery-ui-timepicker-addon.js
#= require back/jquery-ui-timepicker-fr.js
#= require back/jquery.pstrength.1.2.js
#= require back/tag-it.min.js
#= require bootstrap
#= require highcharts/highcharts
#= require highcharts/highcharts-more
#= require back/back

#= require_self
